# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
# witty-ub is licensed under the Mulan PSL v2.
# Container-optimized Nginx configuration

# Run in background

pid /run/witty-ub-web/nginx.pid;
error_log /var/log/witty-ub-web/error.log warn;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/witty-ub-web/access.log;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080;
        server_name _;

        root /var/witty-ub/web;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy API requests to Latency Plugin
        location ~ ^/(log_kb|log_file|log_parse_result|aggregated_event|anomalous_event|anomalous_event_chain|log_failure_event_result|failure_mode|task|health_check|docs|openapi.json) {
            proxy_pass http://127.0.0.1:9772;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
