# Copyright (c) Huawei Technologies Co., Ltd. 2023-2025. All rights reserved.
"""PostgreSQL database initialization helpers."""
from __future__ import annotations

from datetime import datetime, timedelta

from sqlalchemy import text

from latency.database.engine import PGManager
from latency.database.models import Base


async def migrate_timestamptz_to_timestamp() -> None:
    """Convert all TIMESTAMPTZ columns to TIMESTAMP (no timezone).

    This keeps timestamp values exactly as they were written, without any
    timezone conversion.  Safe to run multiple times (idempotent).
    """
    async with PGManager.engine().begin() as conn:
        rows = await conn.execute(text(
            "SELECT table_name, column_name "
            "FROM information_schema.columns "
            "WHERE table_schema = 'public' "
            "AND data_type = 'timestamp with time zone'"
        ))
        for table_name, column_name in rows:
            await conn.execute(text(
                f"ALTER TABLE {table_name} "
                f"ALTER COLUMN {column_name} "
                f"TYPE timestamp without time zone"
            ))


async def create_log_parse_result_partitions() -> None:
    """Create 32 HASH partitions for log_parse_result."""
    async with PGManager.engine().begin() as conn:
        for i in range(32):
            await conn.execute(
                text(
                    f"CREATE TABLE IF NOT EXISTS log_parse_result_p{i} "
                    f"PARTITION OF log_parse_result FOR VALUES WITH (MODULUS 32, REMAINDER {i})"
                )
            )


async def create_manual_indexes() -> None:
    """Create GIN / partial indexes that are not auto-generated by SQLAlchemy."""
    indexes = [
        "CREATE INDEX IF NOT EXISTS idx_lpr_pod_ips ON log_parse_result USING GIN (pod_ips) WHERE existed_status = TRUE",
        "CREATE INDEX IF NOT EXISTS idx_lpr_log_id_time ON log_parse_result (log_id, timestamp, src_ip, dst_ip) WHERE existed_status = TRUE",
        "CREATE INDEX IF NOT EXISTS idx_lpr_timestamp ON log_parse_result (timestamp) WHERE existed_status = TRUE",
        "CREATE INDEX IF NOT EXISTS idx_lpr_cluster ON log_parse_result (cluster_name, aggregated_event_id) WHERE existed_status = TRUE",
        "CREATE INDEX IF NOT EXISTS idx_lpr_host ON log_parse_result (host, aggregated_event_id) WHERE existed_status = TRUE",
        "CREATE INDEX IF NOT EXISTS idx_lpr_trace_id ON log_parse_result (trace_id) WHERE existed_status = TRUE AND trace_id IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_lpr_log_total_latency ON log_parse_result (log_id, total_latency) WHERE existed_status = TRUE AND total_latency IS NOT NULL",
        "CREATE INDEX IF NOT EXISTS idx_sdae_log_id ON src_dst_aggregated_event(log_id) WHERE existed_status = TRUE",
        "CREATE INDEX IF NOT EXISTS idx_sdae_src_dst ON src_dst_aggregated_event(src_ip, dst_ip) WHERE existed_status = TRUE",
    ]
    async with PGManager.engine().begin() as conn:
        for idx_sql in indexes:
            await conn.execute(text(idx_sql))


async def init_postgresql_database() -> None:
    """Initialize PostgreSQL: create tables, partitions, indexes.

    当前为 PostgreSQL-only 后端，不再做历史 SQLite/schema 迁移；
    需要保留数据的历史升级请使用外部迁移工具（如 Alembic）。
    """
    async with PGManager.engine().begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    await migrate_timestamptz_to_timestamp()
    await create_log_parse_result_partitions()
    await create_manual_indexes()
